### PR TITLE
Added grunt task and source maps

### PR DESCRIPTION
**Pull request by darylhedley**
- Original 'grunt' task now provides source mapping
- Uglify was removed from it's own task and put into r.js task as it
  comes with it. package.json was updated to reflect this.
- Running 'grunt build' will create a minified version of mylib.js
  using uglify2. This can be switched out easily to uglify by updating
  the gruntfile as uglify also comes with r.js

### CODE REVIEW

**Comment by darylhedley** [comment]
Hey I thought your example was really great. The test setup for Karma was just what I was looking for, so thanks for outlining how you use it.

We use the optimiser for requirejs quite a lot and found that uglify comes with it and also sourcemapping is amazing. It tells me exactly where my errors are occurring and not just from a single minified file.

**Comment by darylhedley** [comment]
Ah yes - sorry I should have done that. I actually have it written like that in a project I'm using. Would you like me to write another one up that doesn't repeat code? - I could even write one that still keeps uglify in the r.js config but will have it's own separate task. Something like this:

```
$ grunt uglify
```

or even just

```
$ grunt
```

could do it. This would save having to download uglify twice.

**Comment by sahat** [comment]
I would prefer to keep it simple, and leave uglify grunt task unchanged. Besides, it provides some extra things that r.js doesn't, e.g. banner comments. So unless it's possible to do this change with the same number of lines as before (or less) in Gruntfile.js, it is better to leave it as two separate tasks. That is conceptually simpler especially for those who are new to Grunt.js.

**Comment by darylhedley** [comment]
Yeah, I agree it's simpler for a beginner to come in and see a separate task - for me, I know that the r.js grunt task is so powerful that I'd rather it was in one task. I believe you can still do the same configs on uglify inside of the r.js config. I would have thought it would be less lines of code to do it that way too - but I'd have to check that.

I'll close this pull request - thanks for setting out the karma config file. I'm going to have a go at using it with Mocha. Don't suppose you know how well it works with travis-ci do you?

**Comment by sahat** [comment]
@darylhedley You should be able to use travi-ci as usual:

```
### .travis.yml
language: node_js
node_js:
  - 0.8
```

And then package.json needs to have

```
'devDependencies': {
  'karma': '~0.8'
},
'scripts': {
   'test': './node_modules/.bin/karma start --single-run --browsers PhantomJS'
}
```

That was copy and pasted from Karma's documentation on how to use it with Travis-CI.

If I have time tomorrow, I will add support for Travis-CI. And Mocha too if I can re-use most of the jasmine testing configuration.

**Comment by darylhedley** [comment]
I tried using mocha and didn't succeed so an example of that would be great. However I switched over to jasmine and it worked straight away. My tests are now completing on travis-ci and across browsers.

**Comment by sahat** [comment]
@darylhedley I have added Travis-CI support and MochaSpecRunner that uses Chai for assertions, as well as support for running mocha tests from Karma.

I have also updated demos.

And lastly, I ended up going your suggested way - running uglify2 from r.js. Unminified code is not that readable anyway, once you include almond.js inside. I have tried to strip down require() and define() from my source code manually, like jQuery library does it, but I had only limited success. It surely would be nice to have Require.js on development side, and production file to be clear of all require/define blocks, almost as if you never even used Require.js.

But current implementation should be more than sufficient for most people that use Require.js.

**Comment by darylhedley** [comment]
That's brilliant. I'm going to test out the mocha example later today and update my project as I moved over to jasmine as I couldn't quite get mocha to work. I'll let you know how I get on.

Also on another note - you could use browserify instead of require.js. This doesn't use requires or defines and instead uses a commonjs syntax. We decided to go with require.js as the documentation and support is great, but something that browserify is missing.

I think you could also remove your uglify dependency in your package.json as it comes with require.js.

Thanks for getting back and putting in a mocha example - this is going to be extremely helpful especially for beginners.

**Pull request closed without merging**
